-- MySQL Script generated by MySQL Workbench
-- Sat May 13 21:36:19 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mathonline
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mathonline
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mathonline` DEFAULT CHARACTER SET utf8 ;
USE `mathonline` ;

-- -----------------------------------------------------
-- Table `mathonline`.`unit_uam`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mathonline`.`unit_uam` (
  `id_unit_uam` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(250) NOT NULL,
  `status` TINYINT NOT NULL,
  PRIMARY KEY (`id_unit_uam`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mathonline`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mathonline`.`user` (
  `id_user` INT NOT NULL AUTO_INCREMENT,
  `user_name` VARCHAR(250) NOT NULL,
  `password` VARCHAR(25) NOT NULL,
  `type_user` INT NOT NULL COMMENT '1.- Administrador\n2.- Profesor\n3.- Alumno',
  `name` VARCHAR(250) NULL,
  `last_name` VARCHAR(250) NULL,
  `sex` INT NULL COMMENT '1.- Hombre\n2.- Mujer',
  `year_birthday` INT NULL,
  `id_unit_uam` INT NOT NULL,
  `email` VARCHAR(250) NOT NULL,
  `uam_identifier` VARCHAR(15) NULL,
  `is_student` TINYINT NULL,
  `is_employed` TINYINT NULL,
  `registration_date` DATETIME NOT NULL,
  `status` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id_user`),
  INDEX `fk_user_unit_uam1_idx` (`id_unit_uam` ASC),
  CONSTRAINT `fk_user_unit_uam1`
    FOREIGN KEY (`id_unit_uam`)
    REFERENCES `mathonline`.`unit_uam` (`id_unit_uam`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mathonline`.`theme`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mathonline`.`theme` (
  `id_theme` INT NOT NULL AUTO_INCREMENT,
  `theme` VARCHAR(250) NOT NULL,
  `status` TINYINT NOT NULL,
  PRIMARY KEY (`id_theme`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mathonline`.`subtopic`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mathonline`.`subtopic` (
  `id_subtopic` INT NOT NULL AUTO_INCREMENT,
  `id_theme` INT NOT NULL,
  `subtopic` VARCHAR(250) NOT NULL,
  `status` TINYINT NOT NULL,
  PRIMARY KEY (`id_subtopic`),
  INDEX `fk_subtopic_theme_idx` (`id_theme` ASC),
  CONSTRAINT `fk_subtopic_theme`
    FOREIGN KEY (`id_theme`)
    REFERENCES `mathonline`.`theme` (`id_theme`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mathonline`.`tutorial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mathonline`.`tutorial` (
  `id_tutorial` INT NOT NULL AUTO_INCREMENT,
  `id_subtopic` INT NOT NULL,
  `tutorial` VARCHAR(250) NOT NULL,
  `status` TINYINT NOT NULL,
  PRIMARY KEY (`id_tutorial`),
  INDEX `fk_tutorial_subtopic1_idx` (`id_subtopic` ASC),
  CONSTRAINT `fk_tutorial_subtopic1`
    FOREIGN KEY (`id_subtopic`)
    REFERENCES `mathonline`.`subtopic` (`id_subtopic`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mathonline`.`blog_tutorials`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mathonline`.`blog_tutorials` (
  `id_user` INT NOT NULL,
  `id_tutorial` INT NOT NULL,
  `time_finish` INT NOT NULL COMMENT 'In seconds',
  `tutorial_date` DATETIME NOT NULL,
  `status` TINYINT NOT NULL,
  PRIMARY KEY (`id_user`, `id_tutorial`),
  INDEX `fk_user_has_tutorial_tutorial1_idx` (`id_tutorial` ASC),
  INDEX `fk_user_has_tutorial_user1_idx` (`id_user` ASC),
  CONSTRAINT `fk_user_has_tutorial_user1`
    FOREIGN KEY (`id_user`)
    REFERENCES `mathonline`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_tutorial_tutorial1`
    FOREIGN KEY (`id_tutorial`)
    REFERENCES `mathonline`.`tutorial` (`id_tutorial`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mathonline`.`question_week`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mathonline`.`question_week` (
  `id_question_week` INT NOT NULL AUTO_INCREMENT,
  `id_user` INT NOT NULL,
  `question` LONGTEXT NOT NULL,
  `status` TINYINT NOT NULL,
  PRIMARY KEY (`id_question_week`),
  INDEX `fk_question_week_user1_idx` (`id_user` ASC),
  CONSTRAINT `fk_question_week_user1`
    FOREIGN KEY (`id_user`)
    REFERENCES `mathonline`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mathonline`.`response_week`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mathonline`.`response_week` (
  `id_response_week` INT NOT NULL AUTO_INCREMENT,
  `id_question_week` INT NOT NULL,
  `response` LONGTEXT NOT NULL,
  `right_wrong` TINYINT NOT NULL,
  `status` TINYINT NOT NULL,
  PRIMARY KEY (`id_response_week`),
  INDEX `fk_response_week_question_week1_idx` (`id_question_week` ASC),
  CONSTRAINT `fk_response_week_question_week1`
    FOREIGN KEY (`id_question_week`)
    REFERENCES `mathonline`.`question_week` (`id_question_week`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mathonline`.`evaluation_tests`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mathonline`.`evaluation_tests` (
  `id_evaluation_tests` INT NOT NULL AUTO_INCREMENT,
  `id_theme` INT NOT NULL,
  `question` LONGTEXT NOT NULL,
  `points` INT NOT NULL,
  `status` TINYINT NOT NULL,
  PRIMARY KEY (`id_evaluation_tests`),
  INDEX `fk_evaluation_tests_theme1_idx` (`id_theme` ASC),
  CONSTRAINT `fk_evaluation_tests_theme1`
    FOREIGN KEY (`id_theme`)
    REFERENCES `mathonline`.`theme` (`id_theme`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mathonline`.`evaluation_response`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mathonline`.`evaluation_response` (
  `id_evaluation_response` INT NOT NULL AUTO_INCREMENT,
  `id_evaluation_tests` INT NOT NULL,
  `response` LONGTEXT NOT NULL,
  `right_wrong` TINYINT NOT NULL,
  `status` TINYINT NOT NULL,
  PRIMARY KEY (`id_evaluation_response`),
  INDEX `fk_evaluation_response_evaluation_tests1_idx` (`id_evaluation_tests` ASC),
  CONSTRAINT `fk_evaluation_response_evaluation_tests1`
    FOREIGN KEY (`id_evaluation_tests`)
    REFERENCES `mathonline`.`evaluation_tests` (`id_evaluation_tests`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mathonline`.`evaluation_test_log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mathonline`.`evaluation_test_log` (
  `id_user` INT NOT NULL,
  `time_finish` INT NOT NULL,
  `score` INT NOT NULL,
  `evaluation_date` DATETIME NOT NULL,
  `status` TINYINT NOT NULL,
  `subtopic_id_subtopic` INT NOT NULL,
  PRIMARY KEY (`id_user`),
  INDEX `fk_user_has_theme_user1_idx` (`id_user` ASC),
  INDEX `fk_evaluation_test_log_subtopic1_idx` (`subtopic_id_subtopic` ASC),
  CONSTRAINT `fk_user_has_theme_user1`
    FOREIGN KEY (`id_user`)
    REFERENCES `mathonline`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_evaluation_test_log_subtopic1`
    FOREIGN KEY (`subtopic_id_subtopic`)
    REFERENCES `mathonline`.`subtopic` (`id_subtopic`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mathonline`.`monthly_theme`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mathonline`.`monthly_theme` (
  `id_monthly_theme` INT NOT NULL AUTO_INCREMENT,
  `id_user` INT NOT NULL,
  `mounth` INT NOT NULL COMMENT '1.- Enero\n2.- Febrero\n3.- Marzo\n12.- Diciembre',
  `title` VARCHAR(500) NOT NULL,
  `description` LONGTEXT NOT NULL,
  `image` VARCHAR(500) NULL,
  `url_video` VARCHAR(250) NULL,
  `status` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id_monthly_theme`),
  INDEX `fk_monthly_theme_user1_idx` (`id_user` ASC),
  CONSTRAINT `fk_monthly_theme_user1`
    FOREIGN KEY (`id_user`)
    REFERENCES `mathonline`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `mathonline`.`unit_uam`
-- -----------------------------------------------------
START TRANSACTION;
USE `mathonline`;
INSERT INTO `mathonline`.`unit_uam` (`id_unit_uam`, `name`, `status`) VALUES (1, 'Ninguna', 1);
INSERT INTO `mathonline`.`unit_uam` (`id_unit_uam`, `name`, `status`) VALUES (2, 'Unidad Azcapotzalco', 1);
INSERT INTO `mathonline`.`unit_uam` (`id_unit_uam`, `name`, `status`) VALUES (3, 'Unidad Cuajimalpa', 1);
INSERT INTO `mathonline`.`unit_uam` (`id_unit_uam`, `name`, `status`) VALUES (4, 'Unidad Iztapalapa', 1);
INSERT INTO `mathonline`.`unit_uam` (`id_unit_uam`, `name`, `status`) VALUES (5, 'Unidad Lerma', 1);
INSERT INTO `mathonline`.`unit_uam` (`id_unit_uam`, `name`, `status`) VALUES (6, 'Unidad Xochimilco', 1);
INSERT INTO `mathonline`.`unit_uam` (`id_unit_uam`, `name`, `status`) VALUES (7, 'Otra Unidad', 1);

COMMIT;

